### ISSUE TITLE
Kanban Board Review

### ISSUE THREAD

**Issue by rpire** [aliabbani/Catalog-of-my-things#28]
### Link
- [Kanban board link](https://github.com/aliabbani/Catalog-of-my-things/projects/1)
### Members
- 3 people are working on this project.
- @aliabbani is *team member 1*.
- @rpire is *team member 2*.
- @medaminedev66 is *team member 3*.

**Comment by henatan99** [comment]
Hi team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


## Required Changes ♻️
- [ ] Nice job so far but it looks like @medaminedev66 forgot to include one task. Your number of tasks is one task short of the other participants. Kindly look at the attached screenshot and add a task you have missed. :pray: 

![image](https://user-images.githubusercontent.com/64894927/142865368-f974b5e3-adaa-485f-b615-cb06bc50ee86.png)

- [ ] The total point added from points allocated for each task, should be balanced between each participant. The total points for each participant in this kanban board are:
    - @rpire : 12 pts
    - @medaminedev66 : 13.75 pts
    - @aliabbani : 31.25 pts
   So, you shouldn't have more than 5 pts difference between each other's total points. Kindly discuss and try to make the total points of the tasks assigned for each participant get balanced. 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by dasileker** [comment]
## **Hi @aliabbani ,** 

## **Congratulations! 🎉 Project Approved ✅**
Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 
 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
